# Generated by Django 5.2.10 on 2026-01-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiGenerationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100, unique=True)),
                ('total_images_generated', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('bodytype', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gemini_generation_stats',
            },
        ),
    ]
