# Generated by Django 5.2.10 on 2026-01-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0002_geminigenerationstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costing',
        ),
        migrations.RenameField(
            model_name='geminigenerationstats',
            old_name='total_images_generated',
            new_name='total_images',
        ),
        migrations.RemoveField(
            model_name='geminigenerationstats',
            name='bodytype',
        ),
        migrations.RemoveField(
            model_name='geminigenerationstats',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='geminigenerationstats',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='geminigenerationstats',
            name='request_id',
        ),
        migrations.AlterModelTable(
            name='geminigenerationstats',
            table=None,
        ),
    ]
