# Generated by Django 5.2.10 on 2026-01-28 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiapp', '0003_delete_costing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('bodytype', models.CharField(max_length=50)),
                ('uploaded_images', models.JSONField()),
                ('generated_images', models.JSONField()),
                ('generated_count', models.PositiveIntegerField()),
                ('cost_per_image', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_images', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGenerationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_summaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GeminiGenerationStats',
        ),
        migrations.AddField(
            model_name='imagegenerationhistory',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='aiapp.imagegenerationsummary'),
        ),
    ]
